### PR TITLE
add polygonize

### PR DESCRIPTION
**Pull request by rafaqz**
Generates polygons from a matrix.

Still needs winding detection to separate exteriors and holes

### CODE REVIEW

**Comment by asinghvi17** [comment]
Hey, is the polygoize function only supposed to distinguish one from zero?  Or should we allow a list of levels as kwargs (perhaps only for the Contours algorithm representation)?

**Comment by rafaqz** [comment]
Good question. I guess matching some condition like `x in 2.1..4.7` or `x == 3` is identical in practice?

So maybe they can all do that.

**Comment by asinghvi17** [comment]
I just took a look at GDAL and it looks like `GDALPolygonize` emits polygons for each unique value in the array.  

We could either do that, and emit polygons with metadata somehow embedded (or return `(polygons, values)`), or say that these functions only work on boolean matrices and move forward with that.  What do you think?

**Comment by rafaqz** [comment]
We could emit Feature objects in a feature collection/Table

**Comment by rafaqz** [comment]
Lets merge this for now so we can use it, I will add more things later

**Pull request merged**
