### PR TITLE
Thread for transformations like reproject, simplify, etc

### PR DESCRIPTION
**Pull request by rafaqz**
Add optional threading to everything that uses `apply`.

Threaded tasks will be used at the outermost level of the object passed in, over a vector of geometries, features in a feature collection, or e.g. polygons in a multipolygon.

See #23

### CODE REVIEW

**Comment by skygering** [comment]
Why are we using a keyword for threaded rather than just making it multithreaded if there is more than one thread available? Is this common practice and will users expect this? Other than that, looks great!

**Comment by rafaqz** [comment]
A few reasons.

We dont actually know how many threads are available any more, because threading can be nested.

If this is running in an already threaded context it may be better to avoid further threading.

But actually, the main reason I added the keyword is because our own code is nested (think a vector of feature collections of multipolygons) and we dont want to keep triggering threading at every level, just the outer one.

Then if we need the keyword anyway for internal use we may as well let users choose as well.

**Comment by skygering** [comment]
That makes sense to me! Thanks for explaining. Happy to see it merged.

**Review by skygering — APPROVED** [review]

**Comment by rafaqz** [comment]
No worries! I also might leave `false` as the default for now in case there are any threading related bugs. That could make debugging other things harder while we build things out.

**Pull request merged**
